language: node_js
node_js:
  - 12
script:
- npm run lint
- npm run build
before_deploy:
- mv .gitignore copy.gitignore
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
after_deploy:
- mv copy.gitignore .gitignore